# Generated by Django 5.0.6 on 2024-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbooks',
            name='cost_list',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Укажите количество страниц'),
        ),
    ]
